### ISSUE TITLE
Make vector hashable

### ISSUE THREAD

**Issue by brendan-rius** [AtheMathmo/rulinalg#10]
Vector does not implement the Hash trait, which makes it - for example - unusable as the key of a HashMap

**Comment by AtheMathmo** [comment]
Thanks for posting the issue!

I appreciate that this is a very quick and easy fix - but could you explain the use case for me? I ask as I don't see anything obvious myself and this will increase compile time (probably negligibly).

Also - would we not want this to also be possible for `Matrix`?

**Comment by brendan-rius** [comment]
In my case, I have a structure containing a vector and I use that structure as the key of my HashMap. To be able to do this, my structure has to implement the `Hash` trait and this Vector needs it too (to be able to use `derive`).

Maybe there are some other use cases but I have not experienced them.
(If it is considered a valid argument, the native `Vec` also implements `Hash`)

**Comment by AtheMathmo** [comment]
I see, thanks! I've added a comment to PR #11 . In short I'm happy to see it added unless there is a significant increase in compile time (which I don't see happening).
