### ISSUE TITLE
The 0.4 release

### ISSUE THREAD

**Issue by AtheMathmo** [AtheMathmo/rulinalg#109]
This issue is to track the work that we should get in as part of the 0.4 release. I'd appreciate it if responsible parties could chime in on when they expect to complete the work. This isn't intended to put pressure on anybody but will let me know if I should take over or push back some of these to the next major version bump. Thank you!

From me:

- [x] #108 
- [x] #107 
- [x] #101 

The metric traits PR needs some reviews but I believe all work is (more or less) ready for merge.

From @Andlon :

<s>- [ ] LU rewrite ( #94 ).

I suspect we will need to push this one back to a 0.5 release later. Included in case you have some time to work on it soon.</s>

Will be pushing this back to 0.5.

From @c410-f3r :

- [x] #82 
- [x] #78

I'd like a minor doc change on #82 but it can be merged without it. And there are some merge conflicts on #78 that needs resolving.

**Comment by Andlon** [comment]
About #94: Yeah, you're right. I've been way too busy lately to finish this up any time soon. Hopefully I'll have time to finish it before 0.5 (ideally along with a reworking of the remaining decompositions too)!

**Comment by AtheMathmo** [comment]
@Andlon that's totally fine. I start my PhD program in January so I suspect I will be very busy too. That's why I want to try and get 0.4 out before then.

I'll note in the description that this one will be pushed to 0.5 .

**Comment by AtheMathmo** [comment]
All the major points are ready now for the 0.4 release. I still want to try and split out the slice module before merging. I'll handle `impl_ops` after. The reason for this is that I am moving the `BaseMatrix` traits into a new `base` module which is a breaking change (though I imagine most people use the reexport in `matrix`.

I need to fix conflicts with that and then will be looking to release! Thanks for your help all, in particular @Andlon and @c410-f3r .
