### ISSUE TITLE
Matrix Row / column wise min/max

### ISSUE THREAD

**Issue by sinhrks** [AtheMathmo/rulinalg#113]
It is convenient if we have row / column-wise ``.min`` and ``.max`` of ``Matrix``. 

- accept ``Axes`` to specify axis like other aggregation funcs.
- min / max logic should be the same as ``argmin / argmax``. (thus requires ``PartialEq``)

**Comment by AtheMathmo** [comment]
I agree that this would be a useful addition. The only issue is that we would require the `PartialEq` trait and so we cannot add this to the `BaseMatrix` trait.

In order to implement this properly we would need column iterators ( #3 ) which are on the way with #84 .

**Comment by AtheMathmo** [comment]
Excuse part of my above comment - we can add this to the `BaseMatrix` trait by adding a `where` clause to the function which requires `T: PartialEq`.

In which case I think this is a solid addition and I would welcome a PR. If you want to work on this feel free to implement the function without column iterators for now. We should use the `Axis` enum to keep things tidy.
