### ISSUE TITLE
Vectors do no support full equality

### ISSUE THREAD

**Issue by brendan-rius** [AtheMathmo/rulinalg#12]
For any vector `v`, `v` is equal to itself.
This is then full equality and the vector needs to implement the trait `Eq`.
Right now vectors only implement `PartialEq`

Apart from logical reason to do this, some traits require `Eq` (for example the trait `Ord`).

**Comment by AtheMathmo** [comment]
Yes I agree that this would be a valuable addition.

Do you think it will also be worth deriving other related `cmp` traits? e.g. `Ord`, `PartialOrd`? It seems these are also implemented for `Vec`.

**Comment by brendan-rius** [comment]
🤔 I do not really know how a vector would be compared to another one, what do you think?
How is it done for the native Vec?

**Comment by AtheMathmo** [comment]
I believe that native `Vec` implements the ordering by doing pairwise comparison. Described by the [example here](https://en.wikipedia.org/wiki/Ordered_vector_space#Examples) under R<sup>n</sup>.

I'm not sure whether we should derive this additional behaviour on `Vector` for now. It may be better to allow the user to decide how to do that kind of comparison.

**Comment by brendan-rius** [comment]
Yes I think it is probably better to give them the choice on that one
