### ISSUE TITLE
Permutation matrices

### ISSUE THREAD

**Issue by Andlon** [AtheMathmo/rulinalg#131]
A [permutation matrix](https://en.wikipedia.org/wiki/Permutation_matrix) is a very special kind of matrix with many applications in mathematics. Within rulinalg, its use is most notable in the LU decomposition: an `n x n` matrix `A` is decomposed such that `PA = LU` where `P` is an `n x n` permutation matrix.

Currently, the permutation matrix returned by our LU decomposition is an ordinary `Matrix` instance, which means it takes O(n<sup>2</sup>) storage and performing the multiplication `P B` for an `n x n` matrix `B` takes O(n<sup>3</sup>) operations.

However, because of its very special structure, a permutation matrix can be stored in O(n) storage, and the multiplication `P B` can be performed in only O(n<sup>2</sup>) operations. In my opinion, these cost savings more than justify having a specialized implementation for permutation matrices.

Most of the implementation of such a permutation matrix is already in place as part of #94. However, I intend to split up #94 so that the permutation matrix implementation can be a separate PR, which can be merged without breaking changes, whereas the full LU re-implementation may have to wait until we want to make a version bump with breaking changes.

I believe the following operations involving permutation matrices need to be supported:

- [x] Construction from an array-representation of a permutation
- [x] Computing the inverse permutation
- [x] Left-multiplying any `BaseMatrix` derivatives (permuting the rows)
- [x] Right-multiplying any `BaseMatrix` derivatives (permuting the cols)
- [x] Multiplication with other permutation matrices
- [x] Functionality to convert into a full `Matrix` (`From` implementation for `Matrix` presumably, or perhaps also a shortcut member function in addition)
- [x] Computing the parity/determinant of the permutation matrix
- [x] `rows()`/`cols()` (replaced with `size()` in #139)
- [x] Swapping rows in the permutation matrix
- [x] NO support for `Add`/`Sub` binary/unary operators (does not make sense for a permutation matrix)

I'm a little apprehensive about adding more matrix types for which multiplication implementations need to be provided, but after having thought about it a lot, I truly believe it is worth the effort for permutation matrices.

Also, the above suggests that perhaps we should have a more general matrix trait on which `BaseMatrix` depends. I.e. something like `MatrixLike` which covers only indexing and `rows`/`cols`.

**Comment by AtheMathmo** [comment]
This is very well written, thank you!

I agree with pretty much everything you said. Just a couple comments:

> However, I intend to split up #94 so that the permutation matrix implementation can be a separate PR,

I think this is a good idea.

> I'm a little apprehensive about adding more matrix types for which multiplication implementations need to be provided

Me too. I agree that if we can get a big performance boost we should do this - but given how well optimized the current implementation is for standard matrices we'll want to benchmark this carefully. We may find that a bad O(n^2) implementation loses out to the smart O(n^3) one in some _moderate_ cases.

> Also, the above suggests that perhaps we should have a more general matrix trait on which `BaseMatrix` depends. I.e. something like `MatrixLike` which covers only indexing and rows/cols.

I think this is also a good idea. In some cases we can simplify algorithms to work on this trait and it lets users easily take advantage of them with their own structures (by implementing the easier and less presumptive `MatrixLike` trait).

A less intrusive approach would be to have `BaseMatrix` depend on some more things as we've discussed before. For example `Index<[usize; 2], Output=T>`. This gives us a little less though.

**Comment by Andlon** [comment]
Completely agree that this needs to be benchmarked. However, I'd be very surprised to see matrix multiplication being faster in any except for perhaps the very smallest matrices, so I'm quite confident it will be a worthwhile addition. Still - bench first :)

> A less intrusive approach would be to have BaseMatrix depend on some more things as we've discussed before. For example Index<[usize; 2], Output=T>. This gives us a little less though.

This probably belongs to a future discussion, but eventually I think we need a hierarchy of traits for this. In particular, for iterative sparse matrix solvers one often works with matrix-free "linear operators" - that is, an operator which acts on a vector and returns a vector of the same size, but it does not have an explicit matrix representation. I can imagine that we might want to construct a trait hierarchy similar to the following in the future:

```
LinearOperator
    MatrixLike
         DenseMatrix (what is currently BaseMatrix)
         SparseMatrix
```

This is also similar to something @c410-f3r suggested somewhere (can't remember where atm).

**Comment by Andlon** [comment]
@AtheMathmo: how much work did you do on the splitting of the binary operators into smaller files? I found myself spending a little bit of time pulling out the permutation work from #94, and I am mostly lacking the `Mul` implementations for an almost complete PR. Just wondering if I should await the PR with the split. Alternatively I could undertake the splitting (or continue it if you've started, I don't remember) myself.

As usual, there's no rush. I have no idea if I'll even have time to work on it at the moment anyway!

**Comment by AtheMathmo** [comment]
Sorry for the delay, moved country and haven't had much spare time!

I didn't tackle the `impl_ops` module yet, sadly. Will try to do so over the weekend if I can find the time.

**Comment by Andlon** [comment]
I expected you would be busy moving, so no worries :) Hope everything is going well!

I hope to have a PR draft ready for this issue later today. So far I just added things to `impl_ops`, but the permutation stuff is mostly located together, so should be easy to rebase or modify inline with however you want to organize the `impl_ops` module!
