### ISSUE TITLE
Use permutation matrices where relevant

### ISSUE THREAD

**Issue by AtheMathmo** [AtheMathmo/rulinalg#140]
We should replace the existing permutation matrix hacks throughout the library with the new `PermutationMatrix` types. Relevant locations:

- [x] LUP decomposition
- [x] Parity function in `matrix/mod.rs`

**Comment by Andlon** [comment]
Just a heads-up in case anyone would want to work on this: please let me know, and we can work together! I'm hoping to be able to come up with a second draft of #94 soon. It will be completely rewritten and rely on the new `PermutationMatrix` struct.

**Comment by AtheMathmo** [comment]
I think this has been completed now, @Andlon ?

**Comment by Andlon** [comment]
I would agree :)
