### ISSUE TITLE
BaseMatrix has no `get` method.

### ISSUE THREAD

**Issue by Andlon** [AtheMathmo/rulinalg#151]
As the title says, `BaseMatrix` has no `get` method, only `get_unchecked`. Is this deliberate or just an omission? I'm rewriting some generic code (mainly forward and back substitution) and I wanted to avoid unsafe code.

**Comment by AtheMathmo** [comment]
This is an ommission, thanks for pointing it out! We might also want to remedy this by requiring an `Index<[usize; 2>` trait bound on `BaseMatrix`? I think the `get` matrix function is a good addition regardless.

**Comment by prismatica** [comment]
Is anyone working on this? If you're looking for help, this looks like a good place to get started!

**Comment by Andlon** [comment]
@prismatica: not to my knowledge. You're welcome to give it a go if you want :)

**Comment by AtheMathmo** [comment]
@prismatica please take it!

If you need any help locating things or implementing the code feel free to comment here.
