### ISSUE TITLE
A simple way to multiply vector by its transpose

### ISSUE THREAD

**Issue by AliusEquinox** [AtheMathmo/rulinalg#156]
Hello,

I do not found a simpler way to multiply a vector by its transpose. The only way a found :

assuming that m is a vector of size 'size'
`let a: Matrix<f64> = Matrix::new(size, 1, m.data().clone()) * Matrix::new(1, size, m.data().clone());`

it could be simpler to write something like
`let a: Matrix<f64> = m * m.transpose();`

**Comment by AtheMathmo** [comment]
You can convert from a `Vector` to a `Matrix` using the [`From`/`Into` conversion traits](https://doc.rust-lang.org/std/convert/trait.From.html).

This code would look like the following:

```rust
let m: Matrix<f64> = m.into()
let a = m * m.transpose();
```

Let me know if that solves your problem :).

**Comment by AliusEquinox** [comment]
it seems to work fine !
thanks
