### ISSUE TITLE
Update rulinalg Github description

### ISSUE THREAD

**Issue by Andlon** [AtheMathmo/rulinalg#159]
The description of rulinalg's Github repo currently says:

> A linear algebra library in Rust designed for machine learning

Although `rulinalg` was originally extracted from `rusty-machine`, there's little to no functionality in `rulinalg` that is specific to machine learning.

Perhaps we should update the description so that potential users don't get discouraged if they don't intend to use it for machine learning?

**Comment by AtheMathmo** [comment]
Yes I think you're right.

I'll update this now (feel free to post here if you have any suggestions for what this should read instead).

**Comment by Andlon** [comment]
I think the new description is sufficient :) I'll close this now!

**Comment by AtheMathmo** [comment]
Thanks for pointing this out!
