### ISSUE TITLE
SVD should return singular values in descending order

### ISSUE THREAD

**Issue by AtheMathmo** [AtheMathmo/rulinalg#17]
Currently the singular values are not ordered though it is convention to do so.

We are currently using the [Golub-Reinsch scheme](http://people.duke.edu/~hpgavin/SystemID/References/Golub+Reinsch-NM-1970.pdf) to compute the singular value decomposition. I don't think there is a way to implicitly order the singular values so we should do a standard sort whilst reordering the columns and rows of the unitary matrices as appropriate.

**Comment by AtheMathmo** [comment]
From issue #40 by @Andlon:

> By the way, as for the ordering of the singular values... It's a bit comparing apples to oranges, since one is measured in flops and the other is essentially memory accesses, but SVD for a square matrix is approx. O(n^3) iirc. You can sort the eigenvalues in O(n log n) time. If using the eigenvalues as the sorting key, you can simultaneously get the sort order of the eigenvectors. If we allocate a new matrix, you can simply loop over all matrix elements, using the obtained sort order of the vectors to obtain each element. Hence, this is merely O(n^2). So, in this case, asymptotically, the sort should be relatively negligible. In practice, sorting is also very fast (or can be very fast, I'm not familiar with Rust's sort in particular), so I expect it also to be more or less negligible. Since you know the final position of each vector, I believe you can also perform the operation in-place in the same amount of time by swapping columns, though I'm too tired to verify. By the way, for this case, it might be a bit of a disadvantage that rulinalg uses row-major matrices.

Doing this afterwards does indeed incur negligible cost - but I was under the impression that there may be squash this cost as part of the SVD algorithm itself. Maybe this is not the case (if so it's no big deal).

I recently added support for column swapping and it turns out it isn't **too much** slower than row swapping (4x slower in my benchmarks - but this was 60ns/iter vs 15ns/iter). I think that swapping columns would be a pretty acceptable approach.

**Comment by Andlon** [comment]
I looked a bit at the code, and I could certainly take a stab at this. I have no idea if there's a way to implicitly order the singular values. I think as a first pass, I'll simply use standard sort and write benchmarks for with and without the sort to see how significant its impact is. Should be a fairly straightforward exercise, I hope.

Also, I'm not sure when I'll have both the time and energy to do this, so if someone else feels called to do it, I'd also be happy to hand it over to someone else. Just let me know!

**Comment by AtheMathmo** [comment]
That's great! Please feel free to take the issue - it's not directly blocking anything so there's no rush. And once it's in we can get PCA working in rusty-machine too!

Your plan sounds good too - the benchmarks will be valuable. If I can help at all feel free to reach out.

Also if you're knowledgeable in SVD algorithms and spot any issues then feel free to make modifications. I'm not confident that the algorithm is totally solid right now - in particular we might want to put in a safety check to stop infinite looping. This definitely doesn't need to be included as part of this issue though.
