### ISSUE TITLE
Using assert_*_equal macros in all tests

### ISSUE THREAD

**Issue by AtheMathmo** [AtheMathmo/rulinalg#175]
We have just merged #163 which gives us flexible scalar comparisons. Currently many of our tests have checks like this:

```rust
let det = lu.det();
let expected_det = 3.0;
let diff = det - expected_det;
assert!(diff.abs() < 1e-6);
```

Instead we can use the new macro:

```rust
assert_scalar_eq!(lu.det(), 3.0, comp = float);
```

This is cleaner and more flexible. To resolve this issue we should convert all existing comparison checks to use the `assert_*_eq!` macros.

**Comment by Andlon** [comment]
I believe this was resolved by #177, so closing this issue.
