### ISSUE TITLE
Matrix debug info is incorrect on docs homepage?

### ISSUE THREAD

**Issue by mwalczyk** [AtheMathmo/rulinalg#181]
On the front page of the documentation [site](https://athemathmo.github.io/rulinalg/doc/rulinalg/index.html), I think there is a small issue in the section titled "Usage". In particular, the notes say:

> The matrices are stored in row-major order. This means in the example above the top row will be [1,2,3].

But when I print out the aforementioned matrix, it displays as:

```
[ 1 2 ]
[ 3 4 ]
[ 5 6 ]
```

So unless I'm missing something, I think the first row would actually be `[ 1 2 ]` right?

**Comment by AtheMathmo** [comment]
You're right, thanks! Will try to change this soon.

**Comment by Andlon** [comment]
Or perhaps @mwalczyk would be interested in contributing a PR to fix this error in the docs? :-)
