### ISSUE TITLE
Have `mean` and `variance` methods return results

### ISSUE THREAD

**Issue by AtheMathmo** [AtheMathmo/rulinalg#20]
These methods can fail and it would be good for this to be recognized in the API.

The `mean` method may _fail_ if the input Matrix is empty - though it may make sense to simply return an empty mean vector in response.

The `variance` method may fail if the input Matrix has only one row/column of data in the working axis. In this case we will end up dividing by zero (as this method computes the unbiased [sample variance](http://mathworld.wolfram.com/SampleVariance.html)). For now we should fail in this case and perhaps later add in a new method for the biased sample variance which will simply return 0 in this case.

**Comment by eugene-bulkin** [comment]
I think returning an empty vector for `mean` called on an empty matrix makes good enough sense. If we are doing an axis-wise mean, then if there are zero vectors along the given axis, the mean vector should have length zero. That seams reasonable.

As for `variance`, it would likely be sufficient to return `Result<Vector<T>, Error>`, and then after we've determined `n`, return an `Error` if `n == 1`, right?

I can knock this out in a quick PR.

**Comment by AtheMathmo** [comment]
> That seams reasonable.

I agree!

And what you suggest for `variance` sounds good too. I look forward to seeing the PR, thanks!
