### ISSUE TITLE
Some print methods of Vector<f64> and Matrix<f64>

### ISSUE THREAD

**Issue by neutronest** [AtheMathmo/rulinalg#21]
Hi.

When I used this library in my own machine learning project, I tried to implement my own method of typing the values of vector<f64> and matrix<f64>, such as : 

`pub fn show_vector_f64(vec: Vector<f64>) {

    print!("[");
    for x in (vec.data()) {
        print!("{},", x);
    }
    print!("]\n");
}
pub fn show_matrix_f64(mat: Matrix<f64>) {

    let row_num = mat.rows();
    let col_num = mat.cols();
    print!("[\n");
    for i in 0..row_num {
        print!("[");
        for j in 0..col_num {
            print!("{},", mat.data()[i*j]);
        }
        print!("]\n");
    }
    print!("]\n");

}`

I'm not sure if it is useful to add them or some similar but more clear code in the library. However it is hard to implement a fmt::Display method to the generic type of Matrix\<T\>, Vector\<T\>, but Matrix\<f64\> and Vector\<f64\> is often used so... maybe it's helpful.

**Comment by AtheMathmo** [comment]
Hey!

Thanks for opening this issue.

There actually is already a `fmt::Display` implementation for `Matrix<T>`. You should be able to simple use:

```rust
println!("{}", mat);
```

You can also control the precision of the printed values (and maybe some other stuff - I forget).

There isn't a `Display` implementation for `Vector<T>` yet. There probably should be though.

Also as a final note both `Vector` and `Matrix` implement the `Debug` trait. So you can always print them using: `println!("{:?}", mat)` - I know that isn't ideal in many cases though.

Let me know if you have any other questions. If not I'll close this and open a new ticket for implementing `Display` on `Vector`.

On another note - I'd love to see the machine learning project you worked on (if it is view-able of course).

**Comment by neutronest** [comment]
Thank you for your nice replying!

I have got the point :). It's ok to close this issue. I'll read the code and document more carefully later. 

As for the machine learning project ---  I want to build a new deep learning framework using Rust. However it's actually a new born and is keeping developing... Of course I'll share the project after it's much more perfect.

Thank you very much. Have a nice day !

**Comment by AtheMathmo** [comment]
I look forward to learning more about it in the future!

Thanks again for opening this. Have opened #22 and closing this.
