### ISSUE TITLE
Implement Display for Vector

### ISSUE THREAD

**Issue by AtheMathmo** [AtheMathmo/rulinalg#22]
As discussed in #21 we should have a `Display` implementation for `Vector`.

We have this currently for `Matrix` but not `Vector`. The implementation should be similar to this one (allowing precision to be specified) but will list the entries in an array with natural line wrapping.

**Comment by eugene-bulkin** [comment]
Would be reasonable to just do something like this, right? If the vector has data `vec![a, b, c]` where `a`, `b` and `c` all impl `Display`, just return `[a b c]`? Should be pretty straightforward from there.

**Comment by AtheMathmo** [comment]
Yes I think this is indeed appropriate. The only other thing worth being aware of is allowing the accuracy of floats to be specified (we do this for `Matrix`).

And as for your edit - I'm not too sure what I meant myself! I believe I just meant we can return the string all on one line and let the user's terminal handle new lines? I'm not too sure how this part of Rust works but it seems like an acceptable start point?

**Comment by eugene-bulkin** [comment]
Would you think it's a good idea to use a `max_datum_width` size as in `Matrix`? I feel like since the vector can have arbitrary length it may introduce unnecessary whitespace, e.g. if the vector was something like `vec![1000000000, 1, 2, 3]`.

**Comment by AtheMathmo** [comment]
I agree with you, I don't think it really helps the user in this case. Let's just keep a space after each comma.

**Comment by eugene-bulkin** [comment]
Makes sense. I'll take a look at this; I'll try to get something PR'd before Rustconf :)

**Comment by AtheMathmo** [comment]
Awesome, thank you!
