### ISSUE TITLE
Implement `IndexMut` for `Vector<T>`

### ISSUE THREAD

**Issue by tokahuke** [AtheMathmo/rulinalg#37]
This example would not compile:

```rust
let mut x = Vector::new(vec![0; 10]);

for i in 0..10 {
     x[i] = i;
}
```

The compiler complains that "cannot assign to immutable indexed content". This is because only `Index` is implemented for `Vector<T>`. Looking in the docs, `IndexMut` is clearly missing. By now, the workaround I have found was:

```rust
let mut x = Vector::new(vec![0; 10]);

for i in 0..10 {
     x.mut_data()[i] = i;
}
```
which does compile.

**Comment by AtheMathmo** [comment]
You're right!

This one was somehow missed.. I should be able to get in a PR for this in the next couple days - unless you would like to?

**Comment by tokahuke** [comment]
I am doing it right away! This is very trivial.

**Comment by AtheMathmo** [comment]
Great, thank you very much!
