### ISSUE TITLE
matrix! macro does not allow empty matrix construction

### ISSUE THREAD

**Issue by AtheMathmo** [AtheMathmo/rulinalg#64]
One would expect the `matrix!` macro to allow the creation of empty matrices: `let empty_mat = matrix![]`. However currently this fails to compile as there are multiple viable interpretations of the macro.

**Comment by AtheMathmo** [comment]
This seems like something @Andlon may want to look into. Personally I'm not sure how to fix other then bringing back the `count!` macro we used internally before.

Perhaps we could find the `vec!` implementation and copy what they do there.

**Comment by Andlon** [comment]
Ah, forgot to take this into account. I haven't looked into it, but I hope it should be possible to handle that pattern explicitly in the macro definition? (In the sense that a macro matches on a number of patterns) I'll try to take a look later this week!
