### ISSUE TITLE
Implement `get_row` methods for Matrix and MatrixSlices

### ISSUE THREAD

**Issue by AtheMathmo** [AtheMathmo/rulinalg#7]
It would be nice if we could implement a `get_row` method to get a slice of a single row from a Matrix. Something like the following:

```rust
impl Matrix<T> {
    pub fn get_row(&self, idx: usize) -> &[T] {}

    pub fn get_row_mut(&mut self, idx: usize) -> &mut [T] {}
}
```

The contents of the method will need to be unsafe as we'll have to play with pointers a little within the slices. The above methods should do safety checks to ensure the indices are within the right range.

It may also be useful to implement unsafe `get_row_unchecked` and `get_row_unchecked_mut` which can be reused in the above methods.

The code in the [`iter_rows` methods](https://github.com/AtheMathmo/rulinalg/blob/054d7361d38401c500b46f68e526c9a468338655/src/matrix/iter.rs) can likely be adapted to produce the `get_row` methods etc.

**Comment by tafia** [comment]
I think we should probably follow rust `slice` style (with a `Some`). 
```rust
pub fn get_row(&self, idx: usize) -> Some(&[T]) {}
pub fn get_row_mut(&self, idx: usize) -> Some(&mut [T]) {}
unsafe pub fn get_row(&self, idx: usize) -> &[T] {}
unsafe pub fn get_row_mut(&self, idx: usize) -> &mut [T] {}
```
What do you think?

**Comment by AtheMathmo** [comment]
Yes I think you are right. It seems that `get` methods should return an `Option` if they may fail to meet a criteria.

_Minor note: the unsafe method names should be `get\_row\_unchecked_`

**Comment by tafia** [comment]
Yes of course
I'll do it then, probably today

**Comment by AtheMathmo** [comment]
That would be awesome! If you need any help feel free to reach out here or on [gitter](https://gitter.im/AtheMathmo/rusty-machine).
