### ISSUE TITLE
BaseMatrix and BaseMatrixMut operations should not require same type

### ISSUE THREAD

**Issue by andrewcsmith** [AtheMathmo/rulinalg#70]
In [slice.rs](https://github.com/AtheMathmo/rulinalg/blob/master/src/matrix/slice.rs#L361) there are function signatures such as `elemul` that require the same type for both sides of the operation. This leads to pretty silly code as you can't do an `elemul` operation with a mut slice on the one side and a normal matrix on the other.

(This issue could probably be tagged "easy," and I'm willing to help review PRs if needed.)

**Comment by AtheMathmo** [comment]
The reason for this (I believe) is that the `elemul` operation is significantly more efficient if we can guarantee that the data is entirely contiguous, as with the `Matrix` case. Without [specialization](https://github.com/rust-lang/rust/issues/31844) the only way to tackle this special case is by limiting the signature as you describe and doing a separate implementation for `Matrix`.

@tafia may remember better than I do.

To get around this it is probably best to cast types to slices, i.e. for a mut slice and a matrix, use `as_mut_slice()` on the matrix (borrow checker permitting).

If you have any other suggestions, please let me know. If you do want to try changing the signature that's fine, but record benchmarks to make sure there's no regression.

**Comment by tafia** [comment]
Yes there are many places where we got bitten by the lack of
specialisation.
But if you manage to build it without loosing performance I'm interested!

**Comment by andrewcsmith** [comment]
Ah, got it. Didn't see `as_mut_slice()` before, but that clears up some code.

It sounds like specialization is going to happen sooner or later, so maybe hold off and only fix this once. For now it just necessitates wordy workarounds.
