### ISSUE TITLE
Updates to Metric trait

### ISSUE THREAD

**Issue by AtheMathmo** [AtheMathmo/rulinalg#81]
The current [`Metric`](https://athemathmo.github.io/rulinalg/doc/rulinalg/trait.Metric.html) trait is pretty lackluster. It has a `norm` function which computes the euclidean norm. We could do a lot more to flesh it out. This issue is to open discussion about what this trait should support.

Some suggestions:

- Adding L-norms.
   - How should we define `L`, usize, float, enum?
   - How would the [L^infinity norm](http://mathworld.wolfram.com/L-Infinity-Norm.html) be defined?
- Should we directly allow distances (i.e. metrics...). Perhaps we should split out the norms into a new trait and use this trait in the definition of `Metric`: `pub trait Metric : Norm`.
- We could cover **a lot** here. Where should we define our limit?

In rusty-machine we often want to define a metric to be used as a prediction/classification error. For example we can choose the metric in k-means used to compute distance between elements in each set. It would be nice if we could provide a trait in rulinalg which we can be freely generic over in rulinalg.

Any work defined from this issue would be a breaking change - we should aim to include these in a 0.4 release.

**Comment by AtheMathmo** [comment]
After thinking on this a little more I like the second suggestion. I think changing the current trait to `Norm` and having a new `Metric` trait is the best approach. Then #71 can interact more readily with the `Metric` trait.

**Comment by Andlon** [comment]
> In rusty-machine we often want to define a metric to be used as a prediction/classification error. For example we can choose the metric in k-means used to compute distance between elements in each set. It would be nice if we could provide a trait in rulinalg which we can be freely generic over in rulinalg.

I don't quite understand what you mean here. Would you be able to sketch out some short pseudo code for how you would like to use this `Metric` trait in `rusty-machine`? (as you know I'm not so familiar with machine learning, though I have some vague notions of how k-means work)

I also definitely agree with the need for the `Norm` trait, as being able to compute L<sub>pq</sub> norms for matrices (and L<sub>p</sub> norms for vectors) should be part of rulinalg's repertoire.

**Comment by AtheMathmo** [comment]
> Would you be able to sketch out some short pseudo code for how you would like to use this Metric trait in rusty-machine?

Sure! I'm not too sure how this should look, but imagine we have some trait,

```rust
pub trait Metric {
    pub fn compute_metric<T: Float>(mat_1: Matrix<T>, mat_2: Matrix<T>) -> T;
}
```
We would want to be generic over this trait in our models:

```rust
pub struct KMeansClassifier<M: Metric> {
   /* ... */
   marker: PhantomData<M>
}

impl<M: Metric> KMeansClassifier<M> {
    fn compute_distances(&self, inputs: Matrix<T>, cluster_means: Matrix<T>) {
      for i_row in inputs {
         for c_row in cluster_means {
             let distance = M::compute_metric();
         }
      }
      // Use these distance to allocate each `input` row to its closest `cluster_mean`
   }
}
```

Right now we use euclidean norm by default - but we'd like our users to be able to define their own metrics to determine the distance between points in the dataset. For example you could use [hamming distance](https://en.wikipedia.org/wiki/Hamming_distance) to cluster words in an encoded dictionary (I just made that up, but hopefully it illustrates the point).

I don't think that the `Metric` trait should necessarily look like this. It would be nice if we could tackle this use case too though - allowing users to define their own metrics that slide into rusty-machine and rulinalg sensibly. For now I was imagining the `Norm` trait specifying a bunch of norms, and the `Metric` trait using these norms to compute distances between two matrices.

**Comment by AtheMathmo** [comment]
I was playing with this and trying to make it super generic. The idea was to create unit structs like `Euclidean`, etc. and implement `Norm` on these. But for this to work the `Norm` trait needs to work on all of `Matrix`, `MatrixSlice*`, and `Vector`. Without adding a new trait which covers all of these we would need specialization (I think).

Suggestions:

- Only implement for `BaseMatrix` implementors. Perhaps provide a `norm` function on `Vector` for back compatibility.
- Just make `Norm` implement a number of standard norms as trait functions, `euclidean`, `l_norm`, etc.
- Wait for specialization to land.
- Wait for `Impl Trait` return types and use this for `Metric` trait.

I'm leaning towards the first option - but it means more breaking changes further down the line.

Any other ideas?
