### ISSUE TITLE
Typo in get_row_unchecked docs

### ISSUE THREAD

**Issue by AtheMathmo** [AtheMathmo/rulinalg#85]
In the docs we write:

> Returns the row of a matrix at the given index without doing unbounds checking

Instead should read:

> Returns the row of a matrix at the given index without doing any bounds checking

**Comment by saksham15082** [comment]
where are the docs?

**Comment by Andlon** [comment]
@saksham15082: thanks for your interest! The documentation resides inline with the code, and can be built with `cargo doc` as is usual with Rust packages. You can find the relevant line here, in the `src/matrix/slice.rs` file: https://github.com/AtheMathmo/rulinalg/blob/12cf949cb746c37fc7aae52084f1d00e6c9a5483/src/matrix/slice.rs#L101
