### ISSUE TITLE
Add clBLAS and clSPARSE bindings

### ISSUE THREAD

**Issue by c410-f3r** [AtheMathmo/rulinalg#89]
Similar to #15, would be nice to add [clBLAS](https://github.com/clMathLibraries/clBLAS) and [clSPARSE](https://github.com/clMathLibraries/clSPARSE) bindings, which are OpenCL libraries freely available for general public developed by AMD.
Adding bindings to those libs would require much research and effort but I think it is something to consider in the long term.

More info:
[Benchmarking clBLAS SGEMM on the AMD FirePro™ Professional Graphics Card](http://developer.amd.com/community/blog/2015/06/23/benchmarking-clblas-sgemm-on-the-amd-firepro-professional-graphics-card/)
[Open Source clSPARSE Beta Released, Library Accelerates Performance](http://developer.amd.com/community/blog/2015/08/05/clsparse-beta-released/)
[AutoGemm: A flexible and high-performance solution to multiplying matrices](http://developer.amd.com/community/blog/2015/11/05/autogemm-a-flexible-and-high-performance-solution-to-multiplying-matrices/)

**Comment by c410-f3r** [comment]
ArrayFire has rust bindings and is much more tangible than writing the whole GPU thing by hand.
I am closing this issue in favour of ArrayFire.

**Comment by AtheMathmo** [comment]
I have been playing with ArrayFire lately to get a feel for how we could use it to give rulinalg easy access to all of this.

ArrayFire is very easy to use but I'm not convinced it would provide a good solution as part of rulinalg just yet. The issue for me mostly is the fact that `Array`s are not typed. Rulinalg supports generic data types throughout but managing this with an untyped array is very tricky. The error handling is also quite difficult to make use of - but I think this is more a consequence of them using different devices and the ffi bindings.

All that is to say, I'm keeping my eye on it but not quite ready to put the time in yet.

**Comment by Andlon** [comment]
I'm not entirely convinced of the advantages of GPU for general purpose linear algebra. My impression is that it can be faster in some very specialized scenarios that allow for massive fine-grained parallelism, but in general the performance benefits seem to be either:

- Not worth the vast added complexity.
- Outright negative due to overhead of memory transfer and lack of parallelism for the given problem.

Unfortunately most benchmarks I've seen for general linear algebra have been e.g. a top-of-the-line GPU vs a *single core* of some generic CPU, and even in those cases the performance benefits are often only on the order of 10x. Extrapolating from these results, a top-of-the-line CPU would usually performance equally as well.

I would however be very happy to be convinced otherwise, because playing with GPUs sure seems like fun :)

**Comment by AtheMathmo** [comment]
I can't speak too strongly about general purpose linear algebra - I'm not sure how well most algorithms work on a GPU. However matrix multiplication definitely benefits hugely from using a GPU, and I'd imagine other arithmetic operations also see gains.

Either way, expanding rulinalg to use blas/lapack/cuda/opencl is something I'm not too sure how to achieve right now. I have some vague ideas but I'm happy to try and provide efficient Rust code for now (which is really fun!).

**Comment by Andlon** [comment]
That's interesting to hear, @AtheMathmo! Still, as far as I know, this only holds true for particularly large matrices. If the matrices are not sufficiently big the CPU might outperform GPU by a potentially relatively large margin. Hence, I believe one should not generally replace all matrix-matrix multiplication by GPU outright, but rather let it be something the user actively opts in to for problems for which it truly makes sense. My point is that I think it does not make sense to provide a GPU backend for `rulinalg` which accelerates e.g. *all* matrix-matrix multiplication. Of course, one could accelerate only products of sufficiently large matrices, but then one has a non-trivial problem of automatically determining which matrices are "large enough". I think it's better for the user to make this decision.

In any case, providing different backends is fairly difficult, as you said. Even providing e.g. BLAS bindings is far from trivial, and it's a bit of an open question how best to make it work. I know it's a topic in e.g. `nd-array` and other crates. It seems we are quite happy with providing our own (somewhat suboptimal) implementations at the moment. We might just wait it out - let the other guys figure out how best to do it :-P
